admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

_iphp_rubrics:
    resource: .
    type: iphp_rubric

_inlineedit:
    resource: "@IphpCoreBundle/Resources/config/routing/inlineedit.xml"
    prefix:   /_inlineedit



